services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: budzetownik_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - budzetownik

  web:
    image: nginx:stable-alpine
    container_name: budzetownik_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default_nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - budzetownik

  db:
    image: mysql:8
    container_name: budzetownik_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - budzetownik

networks:
  budzetownik:

volumes:
  dbdata:
